<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/1ab94d0eba.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="../../public/CSS/styleRegister.css">
    <title>Formulário</title>
</head>
<body>
    <main>
        <h1>Update Account</h1>

        <form action="/user/update/<?= $user['id'] ?>" method="POST">
       
                <label for="nome">
                    <span>Name</span>
                    <input type="text" id="nome" name="nome" value="<?= $user['nome'] ?>">
                </label>

                <label for="email">
                    <span>E-mail</span>
                    <input type="email" id="email" name="email" value="<?= $user['email'] ?>">
                </label>

                <label for="senha">
                    <span>Password</span>
                    <input type="password" id="senha" name="senha" value="">
                </label>
              
            <input type="submit" value="Update" id="button">
        </form>
    </main>
    <section class="images">
        <img src="../../public/assets/mobile.svg" alt="Mobile">
        <div class="circle"></div>
    </section>
</body>
</html>