<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Lista</title>
</head>
<body>
<h1>USUARIOS</h1>   

<a href="/login/logout">Sair</a>
     
    <?php  foreach($response as $user) { ?>
       <p> NOME:  <?= $user['nome'] ?> </p> 
       <p> EMAIL: <?= $user['email'] ?>  </p>
       <p> SENHA: <?= $user['senha'] ?> </p>

        <a href="/user/delete/<?= $user['id']; ?>">Excluir</a>
        <a href="/user/update/<?= $user['id']; ?>">Editar</a>
            <hr>

    <?php  } ?>
        
    
</body>
</html>






