<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/1ab94d0eba.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="../../public/CSS/styleLogin.css">
    <title>Show</title>
</head>
<body>
    <main class="container">
    <?php echo $response ? '<h1>Registered Successfully</h1>' : '<h1>Failed To Store Data</h1>'; ?>
    
        <form action="/user/visualize" method="POST"> 
            
                   <p>NOME :   <?=$user['nome'] ?></p>
                   <p>EMAIL :  <?=$user['email'] ?></p>
                   <p>SENHA :  <?=$user['senha'] ?></p> 
                    
            <input type="submit" value="See all users">
        </form>
    </main>
</body>
</html>